const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")})},{threshold:.12});
document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const id=a.getAttribute("href");if(id.length>1){e.preventDefault();document.querySelector(id)?.scrollIntoView({behavior:"smooth"})}}));

const level=document.getElementById("level"), program=document.getElementById("program"), schoolFields=document.getElementById("schoolFields"), subjects=document.getElementById("subjects");
const options={school:["School Tuition — Class 9–12"],jee:["JEE Main & Advanced Preparation"],neet:["NEET Preparation"],jam:["IIT JAM Physics Preparation"],net:["CSIR-UGC NET / NET Physics Preparation"],gate:["GATE Physics Preparation"],govt:["Government Examination — General Science / Physics / Mathematics"],bsc:["BSc Physics","BSc Mathematics"],msc:["MSc Physics"],project:["Project Guidance","Research Guidance","Physics Project","Mathematics Project"]};
const subjectMap={school:["Physics","Chemistry","Mathematics","Physics + Chemistry + Mathematics"],jee:["Physics","Chemistry","Mathematics","Physics + Chemistry + Mathematics"],neet:["Physics","Chemistry","Physics + Chemistry"],jam:["Physics","Mathematical Physics"],net:["Physics","Mathematical Physics","Advanced Physics"],gate:["Physics","Mathematical Physics","Advanced Physics"],govt:["Physics","Mathematics","General Science","Quantitative Aptitude / Basic Mathematics"],bsc:["Physics","Mathematics"],msc:["Advanced Physics","Mathematical Physics"],project:["Project / Research topic"]};
function fill(sel,items,placeholder){sel.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option>${x}</option>`).join("")}
level.addEventListener("change",()=>{const v=level.value;fill(program,options[v]||[],"Choose program");fill(subjects,subjectMap[v]||["Physics"],"Choose subject / focus");schoolFields.classList.toggle("hidden",v!=="school")});
document.getElementById("registrationForm").addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.target);const msg=`Hello Narendra Sir, I want to register for tuition/coaching.%0A%0AStudent: ${encodeURIComponent(d.get("name"))}%0APhone: ${encodeURIComponent(d.get("phone"))}%0AEmail: ${encodeURIComponent(d.get("email")||"Not provided")}%0ALevel: ${encodeURIComponent(d.get("level"))}%0AClass: ${encodeURIComponent(d.get("class")||"N/A")}%0ABoard: ${encodeURIComponent(d.get("board")||"N/A")}%0AProgram: ${encodeURIComponent(d.get("program"))}%0ASubject/Focus: ${encodeURIComponent(d.get("subjects"))}%0AMode: ${encodeURIComponent(d.get("mode"))}%0AMessage: ${encodeURIComponent(d.get("message")||"Not provided")}`;window.open(`https://wa.me/919880875618?text=${msg}`,"_blank")});
const menu=document.querySelector(".menu");menu?.addEventListener("click",()=>document.querySelector(".nav nav").classList.toggle("open"));